# Generated by Django 3.1 on 2021-08-15 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0002_memberloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberloan',
            name='amount_applying',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='memberloan',
            name='approve_or_decline',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Decline', 'Decline'), ('Pending Review', 'Pending Review')], default='Pending Review', max_length=50),
        ),
        migrations.AddField(
            model_name='memberloan',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memberloan',
            name='loan_type',
            field=models.ForeignKey(default='Normal Loan', on_delete=django.db.models.deletion.CASCADE, to='mikopo.loantype'),
        ),
    ]
