# Generated by Django 3.1 on 2021-08-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_group_year'),
        ('mikopo', '0003_auto_20210815_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberLoan',
            new_name='MemberLoanApplication',
        ),
    ]
