# Generated by Django 3.1 on 2021-08-15 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_group_year'),
        ('mikopo', '0004_auto_20210815_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applying', models.FloatField(default=0)),
                ('approve_or_decline', models.CharField(choices=[('Approve', 'Approve'), ('Decline', 'Decline'), ('Pending Review', 'Pending Review')], max_length=50)),
                ('date_applied', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_loans', to='data.group')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikopo.loantype')),
            ],
        ),
    ]
