# Generated by Django 3.1 on 2021-08-15 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_group_year'),
        ('mikopo', '0006_personalloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount_applied', models.FloatField(default=0)),
                ('amount_awarded', models.FloatField(default=0)),
                ('disbursed_by', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank', 'Bank'), ('Cash', 'Cash')], default='Cash', max_length=200)),
                ('date_awarded', models.DateField(default=django.utils.timezone.now)),
                ('repay_by', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_awarded_loans', to='data.group')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mikopo.loantype')),
            ],
        ),
    ]
