# Generated by Django 3.1 on 2021-08-15 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_group_year'),
        ('mikopo', '0007_grouploan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPersonalLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikopo.personalloan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
    ]
