# Generated by Django 3.1 on 2021-08-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0009_paygrouploan'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalloan',
            name='amount_repaid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='personalloan',
            name='amount_to_repay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='personalloan',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
