# Generated by Django 3.1 on 2021-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0010_auto_20210815_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loans_awarded', models.FloatField(default=0)),
                ('loans_repayment', models.FloatField(default=0)),
            ],
        ),
    ]
