# Generated by Django 3.1 on 2021-08-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0013_auto_20210815_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouploan',
            name='interest_rate',
            field=models.IntegerField(default=16, editable=False),
        ),
        migrations.AddField(
            model_name='personalloan',
            name='interest_rate',
            field=models.IntegerField(default=10),
        ),
    ]
