# Generated by Django 3.1 on 2021-08-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0014_auto_20210816_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalloan',
            name='interest_rate',
            field=models.IntegerField(choices=[('Short Loan', ((15, 15),)), ('Emergency Loan', ((5, 5),)), ('Normal Loan', ((15, 15),)), ('Development Loan', ((10, 10),)), ('Group Loan', ((16, 16),))], default=10),
        ),
    ]
