# Generated by Django 3.1 on 2021-08-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0015_auto_20210816_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouploan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='interest_rate',
        ),
    ]
