# Generated by Django 3.1 on 2021-08-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0016_auto_20210816_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paygrouploan',
            old_name='loan',
            new_name='group_loan',
        ),
        migrations.RenameField(
            model_name='paypersonalloan',
            old_name='loan',
            new_name='personal_loan',
        ),
    ]
