# Generated by Django 3.1 on 2021-08-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0017_auto_20210816_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouploan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
