# Generated by Django 3.1 on 2021-08-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0018_auto_20210816_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypersonalloan',
            name='personal_loan',
        ),
    ]
