# Generated by Django 3.1 on 2021-08-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0019_remove_paypersonalloan_personal_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypersonalloan',
            name='personalloan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mikopo.personalloan'),
        ),
    ]
