# Generated by Django 3.1 on 2021-08-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0020_paypersonalloan_personalloan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouploan',
            name='amount_to_repay',
        ),
        migrations.RemoveField(
            model_name='grouploan',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='amount_to_repay',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='balance',
        ),
    ]
