# Generated by Django 3.1 on 2021-08-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0021_auto_20210816_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_loans', models.FloatField(default=0)),
                ('personal_loans_repayments', models.FloatField(default=0)),
                ('group_loans', models.FloatField(default=0)),
                ('group_loans_repayments', models.FloatField(default=0)),
            ],
        ),
    ]
