# Generated by Django 3.1 on 2021-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0022_loanfinancial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfinancial',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
