# Generated by Django 3.1 on 2021-08-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikopo', '0026_auto_20210816_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfinancial',
            name='group_loans_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loanfinancial',
            name='personal_loans_profit',
            field=models.FloatField(default=0),
        ),
    ]
