# Generated by Django 3.1 on 2021-07-23 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0003_auto_20210722_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=500)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberTotalSaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('amount', models.FloatField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRenewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=500, editable=False)),
                ('date_renewed', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=1500, editable=False)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTotalSaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('amount', models.FloatField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRenewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=0)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=2500, editable=False)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.group')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='late for meeting')),
                ('amount_fined', models.FloatField(default=50)),
                ('date_fined', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
    ]
