# Generated by Django 3.1 on 2021-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprenewal',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=4),
        ),
        migrations.AddField(
            model_name='groupsaving',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=4),
        ),
        migrations.AddField(
            model_name='membershiprenewal',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=4),
        ),
        migrations.AddField(
            model_name='saving',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=4),
        ),
        migrations.AddField(
            model_name='weeklypayment',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=4),
        ),
    ]
