# Generated by Django 3.1 on 2021-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210723_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptotalsaving',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
