# Generated by Django 3.1 on 2021-07-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_grouptotalsaving_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptotalsaving',
            name='title',
        ),
    ]
