# Generated by Django 3.1 on 2021-07-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_grouptotalsaving_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipRenewal',
        ),
    ]
