# Generated by Django 3.1 on 2021-07-23 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_group_year'),
        ('finance', '0007_delete_membershiprenewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRenewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_amount', models.FloatField(default=0)),
                ('date_renewed', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
    ]
