# Generated by Django 3.1 on 2021-07-26 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_group_year'),
        ('finance', '0009_membershiprenewal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChamaExpenditure',
            fields=[
                ('transaction_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('amount_spend', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('date_spend', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.ManyToManyField(to='data.Staff')),
            ],
        ),
    ]
