# Generated by Django 3.1 on 2021-07-28 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaExpenditureLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('amount_spend', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('date_spend', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FineLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member_id', models.CharField(max_length=200)),
                ('reason', models.TextField(default='late for meeting')),
                ('amount_fined', models.FloatField(default=50)),
                ('date_fined', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group_id', models.CharField(max_length=200)),
                ('amount_paid', models.FloatField(default=0)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRenewalLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group_id', models.CharField(max_length=200)),
                ('amount_paid', models.FloatField(default=0)),
                ('year', models.CharField(max_length=4)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSavingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member_id', models.CharField(max_length=200)),
                ('group_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('year', models.CharField(max_length=4)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRegistrationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member_id', models.CharField(max_length=200)),
                ('amount_paid', models.FloatField(default=0)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRenewalLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member_id', models.CharField(max_length=200)),
                ('renewal_amount', models.FloatField(default=0)),
                ('renewal_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SavingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPaymentLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('member_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=500)),
                ('year', models.CharField(max_length=4)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
