# Generated by Django 3.1 on 2021-07-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupRegistration',
            new_name='GroupRegistrationLog',
        ),
    ]
