# Generated by Django 3.1 on 2021-07-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('goup_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('date_formed', models.DateField()),
                ('number_of_members', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('meeting_title', models.CharField(choices=[('Weekly Meeting', 'Weekly Meeting'), ('Monthly Meeting', 'Monthly Meeting'), ('Annual Meeting', 'Annual Meeting'), ('Board Meeting', 'Board Meeting'), ('Emergency Meeting', 'Emergency Meeting')], max_length=200, unique_for_date='meeting_date')),
                ('meeting_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Chama Meetings',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_number', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Binary', 'Binary')], max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary')], max_length=200)),
                ('date_appointed', models.DateTimeField(default=django.utils.timezone.now)),
                ('retirement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.group')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='chairperson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.member'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.member')),
            ],
            options={
                'verbose_name_plural': 'Chama Attendance',
            },
        ),
    ]
